#import <Foundation/Foundation.h>
@interface PodsDummy_Pods_CustomFontAndColors_CustomFontAndColorsUITests : NSObject
@end
@implementation PodsDummy_Pods_CustomFontAndColors_CustomFontAndColorsUITests
@end
